#!/usr/bin/env bash
# Interactive / reproducible TWRP build helper for LG G Pad 7 (v400/v410/v480/v490).
#
# Usage:
#   ./build_twrp.sh --setup --source-dir /mnt/android-source/twrp-lineage-14.1
#   ./build_twrp.sh --sync
#   ./build_twrp.sh --device v400
#   ./build_twrp.sh --device all
#   ./build_twrp.sh                 # interactive menu
#
# Options:
#   --setup              Assert Ubuntu 22.04, install packages, install repo tool,
#                        repo init + local_manifests (requires --source-dir once)
#   --source-dir PATH    Android source tree root (saved to .twrp-build.conf)
#   --sync               repo sync sources
#   --device DEV|all     Build recovery for v400/v410/v480/v490 or all
#   --jobs N             Parallel jobs (default: nproc)
#   --no-clobber         Skip make clobber (faster rebuilds, not release-clean)
#   --release-dir PATH   Where to copy renamed images (default: ~/twrp-releases)
#   -h, --help           Show help

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_FILE="${SCRIPT_DIR}/.twrp-build.conf"
DEVICES=(v400 v410 v480 v490)
MANIFEST_URL="https://github.com/minimal-manifest-twrp/platform_manifest_twrp_lineageos.git"
MANIFEST_BRANCH="twrp-14.1"
LOCAL_MANIFESTS_URL="https://github.com/amdev01/local_manifests.git"
LOCAL_MANIFESTS_BRANCH="cm-14.1-twrp"

DO_SETUP=0
DO_SYNC=0
DEVICE=""
SOURCE_DIR=""
RELEASE_DIR="${HOME}/twrp-releases"
JOBS="$(nproc --all 2>/dev/null || echo 4)"
NO_CLOBBER=0

usage() {
  sed -n '2,20p' "$0"
}

die() { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }
warn() { echo "WARNING: $*" >&2; }

load_conf() {
  if [[ -f "$CONF_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$CONF_FILE"
  fi
}

save_conf() {
  cat >"$CONF_FILE" <<EOF
# Generated by build_twrp.sh — do not commit
SOURCE_DIR="${SOURCE_DIR}"
RELEASE_DIR="${RELEASE_DIR}"
EOF
  info "Saved config to ${CONF_FILE}"
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --setup) DO_SETUP=1 ;;
      --sync) DO_SYNC=1 ;;
      --source-dir)
        shift
        SOURCE_DIR="${1:?--source-dir requires a path}"
        ;;
      --device)
        shift
        DEVICE="${1:?--device requires v400|v410|v480|v490|all}"
        ;;
      --jobs)
        shift
        JOBS="${1:?--jobs requires a number}"
        ;;
      --no-clobber) NO_CLOBBER=1 ;;
      --release-dir)
        shift
        RELEASE_DIR="${1:?--release-dir requires a path}"
        ;;
      -h|--help) usage; exit 0 ;;
      *) die "Unknown option: $1 (try --help)" ;;
    esac
    shift
  done
}

assert_ubuntu_2204() {
  if [[ ! -f /etc/os-release ]]; then
    die "Cannot detect OS (/etc/os-release missing)"
  fi
  # shellcheck disable=SC1091
  source /etc/os-release
  if [[ "${ID:-}" != "ubuntu" || "${VERSION_ID:-}" != "22.04" ]]; then
    die "This setup targets Ubuntu 22.04 (got ${PRETTY_NAME:-unknown}). Refusing --setup."
  fi
  info "OS OK: ${PRETTY_NAME}"
}

install_packages() {
  info "Installing build packages (requires sudo)..."
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    bc bison build-essential ccache curl flex \
    g++-multilib gcc-multilib git gnupg gperf \
    imagemagick lib32ncurses5-dev lib32readline-dev \
    lib32z1-dev liblz4-tool libncurses5 libncurses5-dev \
    libsdl1.2-dev libssl-dev libxml2 libxml2-utils \
    lzop pngcrush rsync schedtool squashfs-tools \
    xsltproc zip zlib1g-dev \
    libwxgtk3.0-gtk3-dev \
    openjdk-8-jdk \
    python2 \
    python3 \
    gcc-10-multilib g++-10-multilib \
    unzip wget
}

install_repo_tool() {
  mkdir -p "${HOME}/bin"
  if [[ ! -x "${HOME}/bin/repo" ]]; then
    info "Downloading Google repo tool to ~/bin/repo..."
    curl -fsSL https://storage.googleapis.com/git-repo-downloads/repo -o "${HOME}/bin/repo"
    chmod +x "${HOME}/bin/repo"
  else
    info "repo tool already present at ~/bin/repo"
  fi
  export PATH="${HOME}/bin:${PATH}"
  if ! grep -q 'HOME}/bin' "${HOME}/.bashrc" 2>/dev/null; then
    echo 'if [ -d "${HOME}/bin" ] ; then PATH="${HOME}/bin:${PATH}" ; fi' >>"${HOME}/.bashrc"
  fi
  # Larger HTTP buffer helps big syncs; does not require user identity.
  git config --global http.postBuffer 524288000 || true
}

setup_source_tree() {
  [[ -n "$SOURCE_DIR" ]] || die "--setup requires --source-dir PATH (e.g. /mnt/android-source/twrp-lineage-14.1)"
  mkdir -p "$SOURCE_DIR"
  SOURCE_DIR="$(cd "$SOURCE_DIR" && pwd)"
  save_conf

  export PATH="${HOME}/bin:${PATH}"
  cd "$SOURCE_DIR"

  if [[ ! -d .repo/manifests ]]; then
    info "repo init (${MANIFEST_BRANCH})..."
    repo init -u "$MANIFEST_URL" -b "$MANIFEST_BRANCH"
  else
    info "repo already initialized — skipping repo init"
  fi

  # Correct location is .repo/local_manifests (roomservice.xml lives at repo root)
  if [[ ! -d .repo/local_manifests/.git ]]; then
    info "Cloning local_manifests (${LOCAL_MANIFESTS_BRANCH})..."
    rm -rf .repo/local_manifests
    git clone -b "$LOCAL_MANIFESTS_BRANCH" "$LOCAL_MANIFESTS_URL" .repo/local_manifests
  else
    info "Updating local_manifests..."
    git -C .repo/local_manifests fetch origin
    git -C .repo/local_manifests checkout "$LOCAL_MANIFESTS_BRANCH"
    git -C .repo/local_manifests pull --ff-only origin "$LOCAL_MANIFESTS_BRANCH" || true
  fi

  if command -v ccache >/dev/null 2>&1; then
    export USE_CCACHE=1
    export CCACHE_EXEC="$(command -v ccache)"
    ccache -M 100G || true
  fi

  info "Setup complete. Next: $0 --sync"
}

ensure_source_dir() {
  if [[ -z "$SOURCE_DIR" ]]; then
    die "SOURCE_DIR not set. Run: $0 --setup --source-dir /path/to/twrp-lineage-14.1"
  fi
  [[ -d "$SOURCE_DIR" ]] || die "SOURCE_DIR does not exist: $SOURCE_DIR"
  SOURCE_DIR="$(cd "$SOURCE_DIR" && pwd)"
  export PATH="${HOME}/bin:${PATH}"
  cd "$SOURCE_DIR"
}

do_sync() {
  ensure_source_dir
  info "repo sync (jobs=${JOBS})..."
  repo sync --jobs="$JOBS" --fetch-submodules --current-branch --no-clone-bundle
  ensure_vendorsetup
  info "Sync complete."
}

ensure_vendorsetup() {
  ensure_source_dir
  local d
  for d in "${DEVICES[@]}"; do
    local dir="device/lge/${d}"
    local vs="${dir}/vendorsetup.sh"
    if [[ ! -d "$dir" ]]; then
      warn "Missing ${dir} — sync may be incomplete"
      continue
    fi
    if [[ ! -f "$vs" ]]; then
      echo "add_lunch_combo lineage_${d}-eng" >"$vs"
      chmod +x "$vs"
      info "Created ${vs}"
    fi
  done
}

set_build_env() {
  export USE_CCACHE=1
  export CCACHE_EXEC="${CCACHE_EXEC:-$(command -v ccache || true)}"
  export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"
  export WITH_TWRP=true
  export CC=gcc-10
  export HOSTCC=gcc-10
  export CXX=g++-10
  # Allow missing deps on minimal TWRP trees
  export ALLOW_MISSING_DEPENDENCIES=true
}

# Extract TW_VERSION_STR from built recovery (compiled from variables.h).
# Full string is TW_MAIN_VERSION_STR + TW_DEVICE_VERSION, e.g. 3.7.0_9-1
# See: https://github.com/TeamWin/android_bootable_recovery commit 9d26b74
# Device suffix comes from TW_DEVICE_VERSION make flag (defaults to "-0").
extract_twrp_version() {
  local product="$1"
  local recovery_bin="${SOURCE_DIR}/out/target/product/${product}/recovery/root/sbin/recovery"
  local twrp_bin="${SOURCE_DIR}/out/target/product/${product}/recovery/root/sbin/twrp"
  local ver=""

  for bin in "$recovery_bin" "$twrp_bin"; do
    if [[ -f "$bin" ]]; then
      ver="$(strings "$bin" 2>/dev/null | grep -E '^[0-9]+\.[0-9]+\.[0-9]+_[0-9]+(-[0-9]+)?$' | head -n1 || true)"
      [[ -n "$ver" ]] && break
    fi
  done

  if [[ -z "$ver" ]]; then
    local variables_h="${SOURCE_DIR}/bootable/recovery/variables.h"
    if [[ -f "$variables_h" ]]; then
      local main_ver
      main_ver="$(grep -E '^\s*#define\s+TW_MAIN_VERSION_STR' "$variables_h" \
        | head -n1 | sed -E 's/.*"([^"]+)".*/\1/')"
      local device_ver="${TW_DEVICE_VERSION:-0}"
      ver="${main_ver}-${device_ver}"
      warn "Could not strings() recovery binary; fell back to variables.h → ${ver}"
    fi
  fi

  [[ -n "$ver" ]] || die "Unable to determine TWRP version string for ${product}"
  echo "$ver"
}

build_device() {
  local product="$1"
  ensure_source_dir
  ensure_vendorsetup
  set_build_env

  info "Building TWRP for ${product} (WITH_TWRP=true, jobs=${JOBS})"

  lunch_device() {
    # envsetup uses unbound vars; temporarily relax nounset
    set +u
    # shellcheck disable=SC1091
    source build/envsetup.sh
    lunch "lineage_${product}-eng"
    set -u
  }

  lunch_device

  if [[ "$NO_CLOBBER" -eq 0 ]]; then
    info "make clobber (clean, reproducible output)..."
    make -j"$JOBS" clobber
    # out/ is gone — re-source envsetup and lunch again
    lunch_device
  else
    warn "Skipping make clobber (--no-clobber)"
  fi

  make -j"$JOBS" recoveryimage

  local img_src="${SOURCE_DIR}/out/target/product/${product}/recovery.img"
  [[ -f "$img_src" ]] || die "Build finished but ${img_src} is missing"

  local ver
  ver="$(extract_twrp_version "$product")"
  local out_name="twrp-${ver}-${product}.img"
  mkdir -p "$RELEASE_DIR"
  local dest="${RELEASE_DIR}/${out_name}"
  cp -f "$img_src" "$dest"
  info "Copied → ${dest}"
  ls -lh "$dest"
}

interactive_menu() {
  echo
  echo "TWRP build menu — LG G Pad 7 (v4xx)"
  echo "  Source:  ${SOURCE_DIR:-<not configured>}"
  echo "  Release: ${RELEASE_DIR}"
  echo
  echo "  1) Build v400"
  echo "  2) Build v410"
  echo "  3) Build v480"
  echo "  4) Build v490"
  echo "  5) Build ALL devices"
  echo "  6) Sync sources"
  echo "  q) Quit"
  echo
  read -r -p "Select: " choice
  case "$choice" in
    1) build_device v400 ;;
    2) build_device v410 ;;
    3) build_device v480 ;;
    4) build_device v490 ;;
    5)
      for d in "${DEVICES[@]}"; do
        build_device "$d"
      done
      ;;
    6) do_sync ;;
    q|Q) exit 0 ;;
    *) die "Invalid selection" ;;
  esac
}

main() {
  load_conf
  parse_args "$@"

  if [[ -n "$SOURCE_DIR" && -d "$SOURCE_DIR" ]]; then
    SOURCE_DIR="$(cd "$SOURCE_DIR" && pwd)"
  fi

  if [[ "$DO_SETUP" -eq 1 ]]; then
    assert_ubuntu_2204
    install_packages
    install_repo_tool
    setup_source_tree
  fi

  if [[ "$DO_SYNC" -eq 1 ]]; then
    do_sync
  fi

  if [[ -n "$DEVICE" ]]; then
    ensure_source_dir
    save_conf
    if [[ "$DEVICE" == "all" ]]; then
      for d in "${DEVICES[@]}"; do
        build_device "$d"
      done
    else
      local ok=0
      for d in "${DEVICES[@]}"; do
        [[ "$DEVICE" == "$d" ]] && ok=1
      done
      [[ "$ok" -eq 1 ]] || die "Unknown device '${DEVICE}' (expected: ${DEVICES[*]}|all)"
      build_device "$DEVICE"
    fi
    exit 0
  fi

  if [[ "$DO_SETUP" -eq 0 && "$DO_SYNC" -eq 0 ]]; then
    ensure_source_dir
    interactive_menu
  fi
}

main "$@"
