#!/usr/bin/env bash
# Unified TWRP / LineageOS 14.1 build helper for LG G Pad 7
# (v400/v410/v480/v490).
#
# The host setup and release directory are shared. TWRP and LineageOS use
# separate source trees because their platform and local manifests differ.
#
# Examples:
#   ./build_v4xx.sh
#   ./build_v4xx.sh --setup
#   ./build_v4xx.sh --type twrp --setup --source-dir /mnt/android/twrp-14.1
#   ./build_v4xx.sh --type lineage --setup --source-dir /mnt/android/lineage-14.1
#   ./build_v4xx.sh --type lineage --sync
#   ./build_v4xx.sh --type lineage --sync --sync-jobs 2
#   ./build_v4xx.sh --type lineage --sync --project kernel/lge/v4xx
#   ./build_v4xx.sh --type lineage --project kernel/lge/v4xx \
#     --project device/lge/v4xx-common
#   ./build_v4xx.sh --type lineage --device v410 --out-tmpfs 48G \
#     --jack-heap 12G --jack-jobs 8
#   ./build_v4xx.sh --type twrp --device all
#   ./build_v4xx.sh --type lineage --device v410 --bootimage
#   ./build_v4xx.sh --type lineage --device v410 --bootimage --magisk \
#     --magisk-apk /path/to/Magisk.apk
#   ./build_v4xx.sh --type lineage --device v410 --magisk \
#     --magisk-apk /path/to/Magisk.apk
#
# Options:
#   --type TYPE          twrp or lineage
#   --setup              Install shared host dependencies; with --source-dir,
#                        also initialize the selected source tree
#   --source-dir PATH    Source tree for the selected type (saved in config)
#   --sync               Sync the selected source tree
#   --project PATH       Sync only this repo path (repeatable; implies --sync).
#                        Same jobs/retries/flags as full sync. Example:
#                        kernel/lge/v4xx or device/lge/v410
#   --device DEV|all     Build v400/v410/v480/v490 or all
#   --jobs N             Parallel build jobs (default: nproc)
#   --sync-jobs N        Parallel repo sync jobs (default: 4; keep low to
#                        avoid android.googlesource.com HTTP 429 rate limits)
#   --sync-retries N     Extra sync attempts on failure (default: 8)
#   --out-tmpfs SIZE     Mount source out/ as tmpfs (e.g. 48G); optional
#   --jack-heap SIZE     Jack server heap (default: 4G)
#   --jack-jobs N        Concurrent Jack tasks (default: 4)
#   --jack-home PATH     Jack server dir (default: <source-parent>/.jack-server
#                        on the source disk; avoids tiny LXC rootfs)
#   --no-clobber         Skip make clobber
#   --bootimage          Build boot.img only (lineage; implies --no-clobber)
#   --magisk             Patch release boot.img with Magisk on the host.
#                        With --bootimage: build then patch. Without: patch
#                        existing lineage-14.1-boot-<device>.img only.
#                        Requires --magisk-apk or saved config.
#   --magisk-apk PATH    Magisk Manager APK for host boot patching (armeabi-v7a
#                        libs required for v4xx)
#   --release-dir PATH   Shared output directory (default: ~/twrp-releases)
#   -h, --help           Show help

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_FILE="${SCRIPT_DIR}/.v4xx-build.conf"
DEVICES=(v400 v410 v480 v490)
LOCAL_MANIFESTS_URL="https://github.com/amdev01/local_manifests.git"

BUILD_TYPE=""
REQUESTED_SOURCE_DIR=""
SOURCE_DIR=""
TWRP_SOURCE_DIR=""
LINEAGE_SOURCE_DIR=""
RELEASE_DIR="${HOME}/twrp-releases"
JOBS="$(nproc --all 2>/dev/null || echo 4)"
# googlesource anonymous quota is easily exhausted at high -j; Lineage wiki
# defaults to -j4. Build jobs stay at nproc separately.
SYNC_JOBS=24
SYNC_RETRIES=8
OUT_TMPFS_SIZE="48G"
JACK_HEAP="24G"
JACK_JOBS=16
JACK_HOME_OVERRIDE=""
DO_SETUP=0
DO_SYNC=0
DEVICE=""
NO_CLOBBER=0
BUILD_BOOTIMAGE=0
PATCH_MAGISK=0
MAGISK_APK=""
SYNC_PROJECTS=()

MANIFEST_URL=""
MANIFEST_BRANCH=""
LOCAL_MANIFESTS_BRANCH=""
LUNCH_VARIANT=""

usage() {
  sed -n '2,55p' "$0"
}

die() { echo "ERROR: $*" >&2; exit 1; }
# Log to stderr so command substitutions (e.g. ensure_magisk_tools) stay clean.
info() { echo "==> $*" >&2; }
warn() { echo "WARNING: $*" >&2; }

load_conf() {
  if [[ -f "$CONF_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$CONF_FILE"
  fi

  # Import paths saved by the older standalone scripts once.
  if [[ -z "$TWRP_SOURCE_DIR" && -f "${SCRIPT_DIR}/.twrp-build.conf" ]]; then
    TWRP_SOURCE_DIR="$(
      unset SOURCE_DIR
      # shellcheck disable=SC1091
      source "${SCRIPT_DIR}/.twrp-build.conf"
      printf '%s' "${SOURCE_DIR:-}"
    )"
  fi
  if [[ -z "$LINEAGE_SOURCE_DIR" && -f "${SCRIPT_DIR}/.lineage-build.conf" ]]; then
    LINEAGE_SOURCE_DIR="$(
      unset SOURCE_DIR
      # shellcheck disable=SC1091
      source "${SCRIPT_DIR}/.lineage-build.conf"
      printf '%s' "${SOURCE_DIR:-}"
    )"
  fi
}

save_conf() {
  {
    echo "# Generated by build_v4xx.sh - do not commit"
    printf 'TWRP_SOURCE_DIR=%q\n' "$TWRP_SOURCE_DIR"
    printf 'LINEAGE_SOURCE_DIR=%q\n' "$LINEAGE_SOURCE_DIR"
    printf 'RELEASE_DIR=%q\n' "$RELEASE_DIR"
    printf 'MAGISK_APK=%q\n' "$MAGISK_APK"
  } >"$CONF_FILE"
  info "Saved config to ${CONF_FILE}"
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --type)
        shift
        BUILD_TYPE="${1:?--type requires twrp|lineage}"
        ;;
      --setup) DO_SETUP=1 ;;
      --sync) DO_SYNC=1 ;;
      --project)
        shift
        [[ -n "${1:-}" ]] || die "--project requires a repo path (e.g. kernel/lge/v4xx)"
        SYNC_PROJECTS+=("$1")
        DO_SYNC=1
        ;;
      --source-dir)
        shift
        REQUESTED_SOURCE_DIR="${1:?--source-dir requires a path}"
        ;;
      --device)
        shift
        DEVICE="${1:?--device requires v400|v410|v480|v490|all}"
        ;;
      --jobs)
        shift
        JOBS="${1:?--jobs requires a number}"
        ;;
      --sync-jobs)
        shift
        SYNC_JOBS="${1:?--sync-jobs requires a number}"
        ;;
      --sync-retries)
        shift
        SYNC_RETRIES="${1:?--sync-retries requires a number}"
        ;;
      --out-tmpfs)
        shift
        OUT_TMPFS_SIZE="${1:?--out-tmpfs requires a size such as 48G}"
        ;;
      --jack-heap)
        shift
        JACK_HEAP="${1:?--jack-heap requires a size such as 12G}"
        ;;
      --jack-jobs)
        shift
        JACK_JOBS="${1:?--jack-jobs requires a number}"
        ;;
      --jack-home)
        shift
        JACK_HOME_OVERRIDE="${1:?--jack-home requires a path}"
        ;;
      --no-clobber) NO_CLOBBER=1 ;;
      --bootimage) BUILD_BOOTIMAGE=1 ;;
      --magisk) PATCH_MAGISK=1 ;;
      --magisk-apk)
        shift
        MAGISK_APK="${1:?--magisk-apk requires a path}"
        ;;
      --release-dir)
        shift
        RELEASE_DIR="${1:?--release-dir requires a path}"
        ;;
      -h|--help) usage; exit 0 ;;
      *) die "Unknown option: $1 (try --help)" ;;
    esac
    shift
  done
}

select_type() {
  local type="$1"
  case "$type" in
    twrp)
      BUILD_TYPE="twrp"
      MANIFEST_URL="https://github.com/minimal-manifest-twrp/platform_manifest_twrp_lineageos.git"
      MANIFEST_BRANCH="twrp-14.1"
      LOCAL_MANIFESTS_BRANCH="cm-14.1-twrp"
      LUNCH_VARIANT="eng"
      SOURCE_DIR="$TWRP_SOURCE_DIR"
      ;;
    lineage)
      BUILD_TYPE="lineage"
      MANIFEST_URL="https://github.com/LineageOS/android.git"
      MANIFEST_BRANCH="cm-14.1"
      LOCAL_MANIFESTS_BRANCH="cm-14.1"
      LUNCH_VARIANT="user"
      SOURCE_DIR="$LINEAGE_SOURCE_DIR"
      ;;
    *) die "Unknown build type '${type}' (expected: twrp|lineage)" ;;
  esac

  if [[ -n "$REQUESTED_SOURCE_DIR" ]]; then
    SOURCE_DIR="$REQUESTED_SOURCE_DIR"
    case "$BUILD_TYPE" in
      twrp) TWRP_SOURCE_DIR="$SOURCE_DIR" ;;
      lineage) LINEAGE_SOURCE_DIR="$SOURCE_DIR" ;;
    esac
  fi
}

assert_ubuntu_2204() {
  [[ -f /etc/os-release ]] || die "Cannot detect OS (/etc/os-release missing)"
  # shellcheck disable=SC1091
  source /etc/os-release
  if [[ "${ID:-}" != "ubuntu" || "${VERSION_ID:-}" != "22.04" ]]; then
    die "This setup targets Ubuntu 22.04 (got ${PRETTY_NAME:-unknown}). Refusing --setup."
  fi
  info "OS OK: ${PRETTY_NAME}"
}

fix_java8_tls() {
  # Jack (cm-14.1) speaks TLS 1.0/1.1. OpenJDK 8u291+ disables those by
  # default, so jack-admin's curl wait hangs / fails with SSL error 35.
  # https://stackoverflow.com/questions/67363030
  local sec=""
  local candidates=(
    /etc/java-8-openjdk/security/java.security
    /etc/java-8-openjdk/jre/lib/security/java.security
  )
  local c
  for c in "${candidates[@]}"; do
    if [[ -f "$c" ]]; then
      sec="$c"
      break
    fi
  done
  [[ -n "$sec" ]] || {
    warn "Could not find java-8 java.security to patch for Jack TLS"
    return 0
  }

  info "Ensuring TLSv1/TLSv1.1 are enabled for Jack in ${sec}"
  sudo python3 - "$sec" <<'PY'
import pathlib, re, sys
path = pathlib.Path(sys.argv[1])
text = path.read_text()

def scrub(s: str) -> str:
    # Remove only TLSv1 and TLSv1.1 tokens (not TLSv1.2 / TLSv1.3).
    s = re.sub(r'(?<![0-9.])TLSv1\.1(?![0-9.])\s*,\s*', '', s)
    s = re.sub(r',\s*(?<![0-9.])TLSv1\.1(?![0-9.])', '', s)
    s = re.sub(r'(?<![0-9.])TLSv1(?![0-9.])\s*,\s*', '', s)
    s = re.sub(r',\s*(?<![0-9.])TLSv1(?![0-9.])', '', s)
    return s

# Match the live property only — not the commented example above it.
new, n = re.subn(
    r'(?m)^(jdk\.tls\.disabledAlgorithms\s*=\s*)(.*?)(\n(?=\S)|\Z)',
    lambda m: m.group(1) + scrub(m.group(2)) + m.group(3),
    text,
    count=1,
    flags=re.S,
)
if not n:
    print(f"ERROR: no jdk.tls.disabledAlgorithms in {path}", file=sys.stderr)
    sys.exit(1)
if new != text:
    path.write_text(new)
    print(f"updated {path}")
else:
    print(f"already OK: {path}")

# Verify TLSv1 / TLSv1.1 are not still listed as disabled tokens.
prop = re.search(
    r'(?m)^jdk\.tls\.disabledAlgorithms\s*=\s*(.*?)(?:\n(?=\S)|\Z)',
    path.read_text(),
    flags=re.S,
)
blob = prop.group(1) if prop else ''
if re.search(r'(?<![0-9.])TLSv1(?:\.1)?(?![0-9.])', blob):
    print(f"ERROR: TLSv1/TLSv1.1 still present: {blob!r}", file=sys.stderr)
    sys.exit(1)
print("jdk.tls.disabledAlgorithms=" + " ".join(blob.split()))
PY
}

install_packages() {
  info "Installing shared TWRP/LineageOS build packages (requires sudo)..."
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    bc bison build-essential ccache curl flex \
    g++-multilib gcc-multilib git git-lfs gnupg gperf \
    imagemagick lib32ncurses5-dev lib32readline-dev \
    lib32z1-dev liblz4-tool libncurses5 libncurses5-dev \
    libsdl1.2-dev libssl-dev libxml2 libxml2-utils \
    lzop pngcrush protobuf-compiler python3-protobuf \
    rsync schedtool squashfs-tools xsltproc xxd zip zlib1g-dev \
    libwxgtk3.0-gtk3-dev openjdk-8-jdk \
    python2 python3 virtualenv \
    gcc-10-multilib g++-10-multilib unzip wget

  fix_java8_tls
  git lfs install || true

  if [[ ! -e /usr/bin/python && -x /usr/bin/python2 ]]; then
    info "Creating /usr/bin/python -> python2 (requires sudo)..."
    sudo ln -sf python2 /usr/bin/python
  fi
}

install_repo_tool() {
  mkdir -p "${HOME}/bin"
  if [[ ! -x "${HOME}/bin/repo" ]]; then
    info "Downloading Google repo tool to ~/bin/repo..."
    curl -fsSL https://storage.googleapis.com/git-repo-downloads/repo \
      -o "${HOME}/bin/repo"
    chmod +x "${HOME}/bin/repo"
  else
    info "repo tool already present at ~/bin/repo"
  fi
  export PATH="${HOME}/bin:${PATH}"
  if ! grep -q 'HOME}/bin' "${HOME}/.bashrc" 2>/dev/null; then
    echo 'if [ -d "${HOME}/bin" ] ; then PATH="${HOME}/bin:${PATH}" ; fi' \
      >>"${HOME}/.bashrc"
  fi
  git config --global http.postBuffer 524288000 || true
  git config --global trailer.changeid.key "Change-Id" || true
}

setup_host() {
  assert_ubuntu_2204
  install_packages
  install_repo_tool
  if command -v ccache >/dev/null 2>&1; then
    ccache -M 100G || true
  fi
}

setup_source_tree() {
  [[ -n "$BUILD_TYPE" ]] || die "--source-dir requires --type twrp|lineage"
  [[ -n "$SOURCE_DIR" ]] || die "A source directory is required"

  mkdir -p "$SOURCE_DIR"
  SOURCE_DIR="$(cd "$SOURCE_DIR" && pwd)"
  case "$BUILD_TYPE" in
    twrp) TWRP_SOURCE_DIR="$SOURCE_DIR" ;;
    lineage) LINEAGE_SOURCE_DIR="$SOURCE_DIR" ;;
  esac
  save_conf

  export PATH="${HOME}/bin:${PATH}"
  cd "$SOURCE_DIR"
  if [[ ! -d .repo/manifests ]]; then
    info "repo init ${BUILD_TYPE} (${MANIFEST_BRANCH})..."
    if [[ "$BUILD_TYPE" == "lineage" ]]; then
      repo init -u "$MANIFEST_URL" -b "$MANIFEST_BRANCH" \
        --git-lfs --no-clone-bundle
    else
      repo init -u "$MANIFEST_URL" -b "$MANIFEST_BRANCH"
    fi
  else
    info "repo already initialized - skipping repo init"
  fi

  if [[ ! -d .repo/local_manifests/.git ]]; then
    info "Cloning local_manifests (${LOCAL_MANIFESTS_BRANCH})..."
    rm -rf .repo/local_manifests
    git clone -b "$LOCAL_MANIFESTS_BRANCH" "$LOCAL_MANIFESTS_URL" \
      .repo/local_manifests
  else
    info "Updating local_manifests (${LOCAL_MANIFESTS_BRANCH})..."
    git -C .repo/local_manifests fetch origin
    git -C .repo/local_manifests checkout "$LOCAL_MANIFESTS_BRANCH"
    git -C .repo/local_manifests pull --ff-only origin \
      "$LOCAL_MANIFESTS_BRANCH" || true
  fi

  info "${BUILD_TYPE} source configured. Next: $0 --type ${BUILD_TYPE} --sync"
}

ensure_source_dir() {
  [[ -n "$BUILD_TYPE" ]] || die "Select --type twrp|lineage"
  [[ -n "$SOURCE_DIR" ]] || die \
    "No ${BUILD_TYPE} source configured. Run --type ${BUILD_TYPE} --setup --source-dir PATH"
  [[ -d "$SOURCE_DIR" ]] || die "SOURCE_DIR does not exist: $SOURCE_DIR"
  [[ -d "$SOURCE_DIR/.repo" ]] || die "Not an Android source tree: $SOURCE_DIR"
  SOURCE_DIR="$(cd "$SOURCE_DIR" && pwd)"
  export PATH="${HOME}/bin:${PATH}"
  cd "$SOURCE_DIR"
}

ensure_vendorsetup() {
  ensure_source_dir
  local d dir vs combo
  for d in "${DEVICES[@]}"; do
    dir="device/lge/${d}"
    vs="${dir}/vendorsetup.sh"
    if [[ ! -d "$dir" ]]; then
      warn "Missing ${dir} - sync may be incomplete"
      continue
    fi
    combo="add_lunch_combo lineage_${d}-${LUNCH_VARIANT}"
    if [[ ! -f "$vs" ]]; then
      echo "$combo" >"$vs"
      chmod +x "$vs"
      info "Created ${vs}"
    elif ! grep -qxF "$combo" "$vs"; then
      echo "$combo" >>"$vs"
      info "Added ${combo} to ${vs}"
    fi
  done
}

sync_sources() {
  ensure_source_dir

  # Re-apply init options for existing Lineage trees too. Without --git-lfs,
  # repo sync can leave large prebuilts (such as webview.apk) as LFS pointers.
  # Skip re-init for single-project syncs (tree already initialized).
  if [[ "$BUILD_TYPE" == "lineage" && ${#SYNC_PROJECTS[@]} -eq 0 ]]; then
    if ! command -v git-lfs >/dev/null 2>&1; then
      info "Installing git-lfs (required for chromium-webview prebuilts)..."
      sudo apt-get update -qq
      sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git-lfs
    fi
    command -v git-lfs >/dev/null 2>&1 ||
      die "git-lfs is required. Install with: apt-get install -y git-lfs"
    info "Enabling Git LFS for the LineageOS source tree..."
    git lfs install
    repo init -u "$MANIFEST_URL" -b "$MANIFEST_BRANCH" \
      --git-lfs --no-clone-bundle
  fi

  # Cap sync parallelism so we do not burn googlesource anonymous quota.
  if [[ "$SYNC_JOBS" -gt 8 ]]; then
    warn "sync-jobs=${SYNC_JOBS} is aggressive; googlesource often returns HTTP 429 above ~4-8"
  fi

  local attempt=1
  local max_attempts=$((SYNC_RETRIES + 1))
  local delay=30
  local rc=0
  local sync_label="${BUILD_TYPE}"
  if [[ ${#SYNC_PROJECTS[@]} -gt 0 ]]; then
    sync_label="${BUILD_TYPE} [${SYNC_PROJECTS[*]}]"
  fi

  while [[ "$attempt" -le "$max_attempts" ]]; do
    info "Syncing ${sync_label} (attempt ${attempt}/${max_attempts}, jobs=${SYNC_JOBS})..."
    set +e
    if [[ "$BUILD_TYPE" == "twrp" ]]; then
      repo sync --jobs="$SYNC_JOBS" --fetch-submodules --current-branch \
        --no-clone-bundle --force-sync "${SYNC_PROJECTS[@]}"
      rc=$?
    else
      repo sync --jobs="$SYNC_JOBS" --current-branch --no-clone-bundle \
        --force-sync "${SYNC_PROJECTS[@]}"
      rc=$?
    fi
    set -e

    if [[ "$rc" -eq 0 ]]; then
      # vendorsetup only matters for device trees; cheap to keep for full sync.
      if [[ ${#SYNC_PROJECTS[@]} -eq 0 ]]; then
        ensure_vendorsetup
      fi
      info "${sync_label} sync complete."
      return 0
    fi

    if [[ "$attempt" -ge "$max_attempts" ]]; then
      die "repo sync failed after ${max_attempts} attempts (last exit ${rc}). Re-run with --sync-jobs 2"
    fi

    warn "repo sync failed (exit ${rc}); likely rate-limit. Sleeping ${delay}s before retry..."
    sleep "$delay"
    # Exponential backoff, capped at 5 minutes
    delay=$((delay * 2))
    if [[ "$delay" -gt 300 ]]; then
      delay=300
    fi
    attempt=$((attempt + 1))
  done
}

set_build_env() {
  export USE_CCACHE=1
  export CCACHE_EXEC="${CCACHE_EXEC:-$(command -v ccache || true)}"
  export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx${JACK_HEAP}"
  # jack-admin start-server reads JACK_SERVER_VM_ARGUMENTS (not ANDROID_JACK_VM_ARGS).
  export JACK_SERVER_VM_ARGUMENTS="$ANDROID_JACK_VM_ARGS"
  # Kept for compatibility with older Jack launchers. Newer Jack servers use
  # jack.server.max-service in config.properties.
  export SERVER_NB_COMPILE="$JACK_JOBS"
  export LC_ALL="${LC_ALL:-C}"
  export CC=gcc-10
  export HOSTCC=gcc-10
  export CXX=g++-10

  # Keep Jack server state + java temp off tiny LXC rootfs (often ~8G).
  # jack-admin honors JACK_HOME (default would be $HOME/.jack-server).
  if [[ -n "$JACK_HOME_OVERRIDE" ]]; then
    export JACK_HOME="$JACK_HOME_OVERRIDE"
  else
    export JACK_HOME="$(dirname "$SOURCE_DIR")/.jack-server"
  fi
  export TMPDIR="$(dirname "$SOURCE_DIR")/.jack-tmp"
  # Client settings stay small in $HOME; server jars/logs go on NVMe.
  export CLIENT_SETTING="${HOME}/.jack-settings"
  mkdir -p "$JACK_HOME" "$TMPDIR"

  if [[ "$BUILD_TYPE" == "twrp" ]]; then
    export WITH_TWRP=true
    export ALLOW_MISSING_DEPENDENCIES=true
  else
    unset WITH_TWRP ALLOW_MISSING_DEPENDENCIES || true
  fi
}

prepare_out_tmpfs() {
  [[ -n "$OUT_TMPFS_SIZE" ]] || return 0
  [[ "$OUT_TMPFS_SIZE" =~ ^[1-9][0-9]*[KMGT]?$ ]] ||
    die "Invalid --out-tmpfs size '${OUT_TMPFS_SIZE}' (example: 48G)"

  local out_dir="${SOURCE_DIR}/out"
  mkdir -p "$out_dir"

  if mountpoint -q "$out_dir"; then
    local fs_type
    fs_type="$(findmnt -n -o FSTYPE --target "$out_dir" 2>/dev/null || true)"
    if [[ "$fs_type" == "tmpfs" ]]; then
      info "${out_dir} is already mounted as tmpfs"
      df -h "$out_dir"
      return 0
    fi
    die "${out_dir} is already a ${fs_type:-non-tmpfs} mount"
  fi

  if [[ -n "$(ls -A "$out_dir" 2>/dev/null)" ]]; then
    warn "Mounting tmpfs will temporarily hide the existing contents of ${out_dir}"
  fi

  info "Mounting ${OUT_TMPFS_SIZE} tmpfs at ${out_dir} (requires sudo)..."
  if ! sudo mount -t tmpfs \
    -o "size=${OUT_TMPFS_SIZE},mode=0755,uid=$(id -u),gid=$(id -g)" \
    tmpfs "$out_dir"; then
    die "Could not mount tmpfs. In an unprivileged LXC, mount it on the host and bind-mount it at ${out_dir}"
  fi
  df -h "$out_dir"
  warn "tmpfs out/ is volatile and remains mounted until unmounted or rebooted"
}

# Set or replace a KEY=VALUE line in a properties-style file.
set_prop_line() {
  local file="$1"
  local key="$2"
  local value="$3"
  touch "$file"
  if grep -q "^${key}=" "$file"; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$file"
  else
    printf '%s=%s\n' "$key" "$value" >>"$file"
  fi
}

configure_jack_server() {
  [[ "$BUILD_TYPE" == "lineage" ]] || return 0
  [[ "$JACK_JOBS" =~ ^[1-9][0-9]*$ ]] ||
    die "Invalid --jack-jobs value '${JACK_JOBS}'"
  [[ "$JACK_HEAP" =~ ^[1-9][0-9]*[KMGT]?$ ]] ||
    die "Invalid --jack-heap value '${JACK_HEAP}' (example: 12G)"

  # JACK_HOME / TMPDIR are set in set_build_env() onto the source disk.
  local jack_home="${JACK_HOME:?JACK_HOME not set}"
  local client_setting="${CLIENT_SETTING:-${HOME}/.jack-settings}"
  local config="${jack_home}/config.properties"
  local jack_admin="${SOURCE_DIR}/prebuilts/sdk/tools/jack-admin"
  local service_port admin_port
  # Per-UID ports avoid clashes on multi-user build servers.
  # See: https://gist.github.com/amdev01/c219a8dea2dc32679a4963ee524f82e3
  service_port=$((UID + 5010))
  admin_port=$((UID + 5160))

  info "Jack home: ${jack_home} (TMPDIR=${TMPDIR})"
  df -h "$jack_home" "$TMPDIR" / 2>/dev/null || true

  # jack-admin aborts with "logs/outputs.txt: No such file or directory"
  # if this folder is missing after a crashed/partial install.
  mkdir -p "${jack_home}/logs" "${jack_home}/jacks" "$TMPDIR"
  touch "$config" "${jack_home}/logs/outputs.txt"
  # Jack refuses to start unless config.properties is exactly mode 0600.
  chmod 600 "$config"

  # jack-admin sources CLIENT_SETTING and requires SETTING_VERSION (nounset).
  # Writing a complete file avoids: "SETTING_VERSION: unbound variable"
  cat >"$client_setting" <<EOF
# Generated by build_v4xx.sh
SETTING_VERSION=4
JACK_SERVER_TIMEOUT=100
SERVER_HOST=localhost
SERVER_PROTOCOL=https
SERVER_PORT_SERVICE=${service_port}
SERVER_PORT_ADMIN=${admin_port}
EOF
  if [[ -f "${HOME}/.jack" ]]; then
    set_prop_line "${HOME}/.jack" "SERVER_PORT_SERVICE" "$service_port"
    set_prop_line "${HOME}/.jack" "SERVER_PORT_ADMIN" "$admin_port"
  fi

  set_prop_line "$config" "jack.server.max-service" "$JACK_JOBS"
  set_prop_line "$config" "jack.server.service.port" "$service_port"
  set_prop_line "$config" "jack.server.admin.port" "$admin_port"
  chmod 600 "$config"

  # Heap and ports are only applied when the server (re)starts.
  # Drop inherited SHELLOPTS so child bash does not keep nounset from us.
  if [[ -x "$jack_admin" ]]; then
    # OpenJDK 8u291+ disables TLS1.0/1.1; Jack's curl handshake then hangs.
    # https://stackoverflow.com/questions/67363030
    fix_java8_tls

    local launcher_jar="${SOURCE_DIR}/prebuilts/sdk/tools/jack-launcher.jar"
    local server_jar
    server_jar="$(ls -1 "${SOURCE_DIR}"/prebuilts/sdk/tools/jack-server-*.jar 2>/dev/null | head -n1 || true)"
    if [[ ! -f "${jack_home}/server.jks" || ! -f "${jack_home}/client.jks" ||
          ! -f "${jack_home}/launcher.jar" ]]; then
      [[ -n "$server_jar" && -f "$launcher_jar" ]] ||
        die "Jack jars missing under prebuilts/sdk/tools"
      info "Installing Jack server into ${jack_home}..."
      env -u SHELLOPTS \
        JACK_HOME="$jack_home" CLIENT_SETTING="$client_setting" TMPDIR="$TMPDIR" \
        "$jack_admin" kill-server >/dev/null 2>&1 || true
      # install-server refuses if JACK_HOME already exists as a directory.
      rm -rf "${jack_home}"
      if ! env -u SHELLOPTS JACK_HOME="$jack_home" TMPDIR="$TMPDIR" \
        "$jack_admin" install-server "$launcher_jar" "$server_jar"; then
        die "jack-admin install-server failed for ${jack_home}"
      fi
      mkdir -p "${jack_home}/logs" "${jack_home}/jacks"
      touch "${jack_home}/logs/outputs.txt"
      # Re-apply server config after fresh install (install leaves mode 0644).
      set_prop_line "${jack_home}/config.properties" "jack.server.max-service" "$JACK_JOBS"
      set_prop_line "${jack_home}/config.properties" "jack.server.service.port" "$service_port"
      set_prop_line "${jack_home}/config.properties" "jack.server.admin.port" "$admin_port"
      chmod 600 "${jack_home}/config.properties"
    fi

    # Ensure mode 0600 even when reusing an existing install (Jack hard-requires it).
    chmod 600 "${jack_home}/config.properties"

    env -u SHELLOPTS \
      JACK_HOME="$jack_home" CLIENT_SETTING="$client_setting" TMPDIR="$TMPDIR" \
      "$jack_admin" kill-server >/dev/null 2>&1 || true
    env -u SHELLOPTS \
      JACK_HOME="$jack_home" CLIENT_SETTING="$client_setting" TMPDIR="$TMPDIR" \
      "$jack_admin" stop-server >/dev/null 2>&1 || true
    # Kill leftover JVMs by cmdline without matching this script's argv via pkill -f.
    ps -eo pid=,args= | awk '/com\.android\.jack\.launcher\.ServerLauncher/ {print $1}' |
      xargs -r kill >/dev/null 2>&1 || true
    sleep 1
    rm -f "${jack_home}/logs/"*.lck

    # Ensure PEM trust anchors exist (jack-admin / curl use these).
    if [[ -f "${jack_home}/server.jks" && ! -s "${jack_home}/server.pem" ]]; then
      keytool -exportcert -alias server -keystore "${jack_home}/server.jks" \
        -storepass Jack-Server -rfc >"${jack_home}/server.pem" 2>/dev/null || true
    fi
    if [[ -f "${jack_home}/client.jks" && ! -s "${jack_home}/client.pem" ]]; then
      keytool -exportcert -alias client -keystore "${jack_home}/client.jks" \
        -storepass Jack-Server -rfc >"${jack_home}/client.pem" 2>/dev/null || true
    fi

    # jack-admin waitServerStarted can hang on TLS failures; bound it with timeout
    # and poll ourselves using SERVER_HOST=localhost (cert CN is localhost).
    info "Starting Jack server (heap=${JACK_HEAP})..."
    : >"${jack_home}/logs/outputs.txt"
    # shellcheck disable=SC2086
    if ! timeout 60s env -u SHELLOPTS \
      JACK_HOME="$jack_home" CLIENT_SETTING="$client_setting" TMPDIR="$TMPDIR" \
      JACK_SERVER_VM_ARGUMENTS="$JACK_SERVER_VM_ARGUMENTS" \
      "$jack_admin" start-server; then
      warn "jack-admin start-server timed out or failed; checking readiness..."
    fi

    curl_rc=1
    info "Waiting for Jack on https://localhost:${admin_port}/server..."
    local i
    for i in $(seq 1 30); do
      curl_rc=0
      curl -fsS --max-time 2 \
        --cert "${jack_home}/client.pem" \
        --cacert "${jack_home}/server.pem" \
        "https://localhost:${admin_port}/server" >/dev/null 2>&1 || curl_rc=$?
      # 0 = OK, 22 = HTTP error but TLS worked (server is up)
      if [[ "$curl_rc" -eq 0 || "$curl_rc" -eq 22 ]]; then
        info "Jack is responding (curl_rc=${curl_rc}, ~${i}s)"
        break
      fi
      if [[ "$i" -eq 2 ]]; then
        local latest_log
        latest_log="$(ls -1t "${jack_home}/logs"/jack-server-*.log 2>/dev/null | head -n1 || true)"
        if [[ -n "$latest_log" && -s "$latest_log" ]]; then
          warn "Jack log so far (${latest_log}):"
          tail -n 20 "$latest_log" >&2 || true
        fi
      fi
      sleep 1
    done

    if [[ "$curl_rc" -ne 0 && "$curl_rc" -ne 22 ]]; then
      warn "Jack failed to become ready; diagnostics:"
      echo "---- ${jack_home}/logs/outputs.txt ----" >&2
      tail -n 40 "${jack_home}/logs/outputs.txt" >&2 || true
      echo "---- latest jack-server-*.log ----" >&2
      ls -1t "${jack_home}/logs"/jack-server-*.log 2>/dev/null | head -n1 |
        xargs -r tail -n 80 >&2 || true
      echo "---- ls -l ${jack_home}/config.properties ----" >&2
      ls -l "${jack_home}/config.properties" >&2 || true
      echo "---- java -version ----" >&2
      java -version >&2 || true
      echo "---- curl probe (localhost) ----" >&2
      curl -v --max-time 5 \
        --cert "${jack_home}/client.pem" \
        --cacert "${jack_home}/server.pem" \
        "https://localhost:${admin_port}/server" 2>&1 | tail -n 40 >&2 || true
      echo "---- jdk.tls.disabledAlgorithms ----" >&2
      grep -a '^jdk.tls.disabledAlgorithms=' \
        /etc/java-8-openjdk/security/java.security 2>/dev/null | head -n1 >&2 || true
      ps -eo pid=,args= | awk '/com\.android\.jack\.launcher\.ServerLauncher/ {print}' >&2 || true
      ps -eo pid=,args= | awk '/com\.android\.jack\.launcher\.ServerLauncher/ {print $1}' |
        xargs -r kill >/dev/null 2>&1 || true
      die "Jack server is not running (curl_rc=${curl_rc})"
    fi

    # Re-assert ports/protocol in case anything rewrote client settings.
    set_prop_line "$client_setting" "SETTING_VERSION" "4"
    set_prop_line "$client_setting" "SERVER_PROTOCOL" "https"
    set_prop_line "$client_setting" "SERVER_PORT_SERVICE" "$service_port"
    set_prop_line "$client_setting" "SERVER_PORT_ADMIN" "$admin_port"
    env -u SHELLOPTS \
      JACK_HOME="$jack_home" CLIENT_SETTING="$client_setting" TMPDIR="$TMPDIR" \
      "$jack_admin" list-server 2>/dev/null || true
  fi
  info "Jack: heap=${JACK_HEAP}, jobs=${JACK_JOBS}, ports=${service_port}/${admin_port}"
}

extract_twrp_version() {
  local product="$1"
  local root="${SOURCE_DIR}/out/target/product/${product}/recovery/root/sbin"
  local ver="" bin
  for bin in "${root}/recovery" "${root}/twrp"; do
    if [[ -f "$bin" ]]; then
      ver="$(strings "$bin" 2>/dev/null |
        grep -E '^[0-9]+\.[0-9]+\.[0-9]+_[0-9]+(-[0-9]+)?$' |
        head -n1 || true)"
      [[ -n "$ver" ]] && break
    fi
  done

  if [[ -z "$ver" && -f "${SOURCE_DIR}/bootable/recovery/variables.h" ]]; then
    local main_ver
    main_ver="$(grep -E '^\s*#define\s+TW_MAIN_VERSION_STR' \
      "${SOURCE_DIR}/bootable/recovery/variables.h" |
      head -n1 | sed -E 's/.*"([^"]+)".*/\1/')"
    ver="${main_ver}-${TW_DEVICE_VERSION:-0}"
  fi
  [[ -n "$ver" ]] || die "Unable to determine TWRP version for ${product}"
  echo "$ver"
}

copy_twrp_artifact() {
  local product="$1"
  local src="${SOURCE_DIR}/out/target/product/${product}/recovery.img"
  [[ -f "$src" ]] || die "Build finished but ${src} is missing"
  local dest="${RELEASE_DIR}/twrp-$(extract_twrp_version "$product")-${product}.img"
  mkdir -p "$RELEASE_DIR"
  cp -f "$src" "$dest"
  info "Copied -> ${dest}"
  ls -lh "$dest"
}

copy_lineage_artifacts() {
  local product="$1"
  local out="${SOURCE_DIR}/out/target/product/${product}"
  local zip
  zip="$(ls -1t "${out}"/lineage-14.1-*-UNOFFICIAL-"${product}".zip \
    2>/dev/null | head -n1 || true)"
  [[ -n "$zip" && -f "$zip" ]] ||
    die "Build finished but no LineageOS zip was found in ${out}"

  mkdir -p "$RELEASE_DIR"
  cp -f "$zip" "${RELEASE_DIR}/$(basename "$zip")"
  info "Copied -> ${RELEASE_DIR}/$(basename "$zip")"
  ls -lh "${RELEASE_DIR}/$(basename "$zip")"

  if [[ -f "${out}/recovery.img" ]]; then
    local recovery="${RELEASE_DIR}/lineage-14.1-recovery-${product}.img"
    cp -f "${out}/recovery.img" "$recovery"
    info "Copied -> ${recovery}"
    ls -lh "$recovery"
  fi
}

copy_lineage_bootimage() {
  local product="$1"
  local src="${SOURCE_DIR}/out/target/product/${product}/boot.img"
  [[ -f "$src" ]] || die "Build finished but ${src} is missing"
  local dest="${RELEASE_DIR}/lineage-14.1-boot-${product}.img"
  mkdir -p "$RELEASE_DIR"
  cp -f "$src" "$dest"
  info "Copied -> ${dest}"
  ls -lh "$dest"
}

magisk_cache_key() {
  local apk="$1"
  local base hash host
  base="$(basename "$apk" .apk)"
  host="$(uname -m)"
  if command -v sha256sum >/dev/null 2>&1; then
    hash="$(sha256sum "$apk" | awk '{print $1}' | cut -c1-12)"
  else
    hash="$(stat -c '%Y-%n' "$apk" | sha256sum 2>/dev/null | awk '{print $1}' | cut -c1-12 ||
      stat -c '%Y' "$apk")"
  fi
  # v2: host magiskboot must not be overwritten by armeabi-v7a libmagiskboot.so
  echo "${base}-${hash}-${host}-v2"
}

magisk_host_lib_dir() {
  local extract_dir="$1"
  case "$(uname -m)" in
    x86_64|amd64)
      if [[ -d "${extract_dir}/lib/x86_64" ]]; then
        echo "${extract_dir}/lib/x86_64"
      elif [[ -d "${extract_dir}/lib/x86" ]]; then
        echo "${extract_dir}/lib/x86"
      fi
      ;;
    i386|i686)
      [[ -d "${extract_dir}/lib/x86" ]] && echo "${extract_dir}/lib/x86"
      ;;
    aarch64|arm64)
      [[ -d "${extract_dir}/lib/arm64-v8a" ]] && echo "${extract_dir}/lib/arm64-v8a"
      ;;
    armv7*|arm)
      [[ -d "${extract_dir}/lib/armeabi-v7a" ]] && echo "${extract_dir}/lib/armeabi-v7a"
      ;;
  esac
}

magisk_hostify_util_functions() {
  local uf="$1"
  [[ -f "$uf" ]] || return 0

  # boot_patch.sh sources util_functions.sh; stub recovery-only helpers on Linux.
  if grep -q '^ui_print()' "$uf"; then
    # Avoid multiline sed replace (easy to corrupt when pasting the script).
    awk '
      BEGIN { skip=0 }
      /^ui_print\(\)/ { print "ui_print() { echo \"[Magisk] $*\"; }"; skip=1; next }
      skip && /^}/ { skip=0; next }
      !skip { print }
    ' "$uf" >"${uf}.tmp" && mv "${uf}.tmp" "$uf"
  else
    printf '%s\n' 'ui_print() { echo "[Magisk] $*"; }' >>"$uf"
  fi

  if ! grep -q '^getprop()' "$uf"; then
    cat >>"$uf" <<'EOF'

getprop() {
  if command -v adb >/dev/null 2>&1 &&
    adb get-state 2>/dev/null | grep -qx device; then
    adb shell getprop "$1" 2>/dev/null || true
  fi
}
EOF
  fi
}

ensure_magisk_tools() {
  local apk="$1"
  local cache_dir stamp extract_dir host_dir arm_dir lib name

  [[ -f "$apk" ]] || die "Magisk APK not found: ${apk}"
  command -v unzip >/dev/null 2>&1 ||
    die "unzip is required for Magisk patching (apt install unzip)"

  cache_dir="${SCRIPT_DIR}/.magisk-tools/$(magisk_cache_key "$apk")"
  stamp="${cache_dir}/.stamp"

  if [[ -f "$stamp" && ! "$apk" -nt "$stamp" &&
        -x "${cache_dir}/magiskboot" && -f "${cache_dir}/boot_patch.sh" ]]; then
    info "Using cached Magisk tools: ${cache_dir}"
    printf '%s' "$cache_dir"
    return 0
  fi

  info "Extracting Magisk tools from ${apk}..."
  mkdir -p "$cache_dir"
  extract_dir="$(mktemp -d /tmp/v4xx-magisk-extract-XXXX)"
  unzip -qo "$apk" -d "$extract_dir"

  [[ -f "${extract_dir}/assets/boot_patch.sh" ]] ||
    die "Magisk APK missing assets/boot_patch.sh"
  cp -f "${extract_dir}/assets/boot_patch.sh" "${cache_dir}/boot_patch.sh"
  # Drop CR and neutralize dos2unix calls (often missing on build hosts).
  sed -i 's/\r$//' "${cache_dir}/boot_patch.sh"
  sed -i 's/\bdos2unix\b/true/g' "${cache_dir}/boot_patch.sh"
  if [[ -f "${extract_dir}/assets/util_functions.sh" ]]; then
    cp -f "${extract_dir}/assets/util_functions.sh" "${cache_dir}/util_functions.sh"
    sed -i 's/\r$//' "${cache_dir}/util_functions.sh"
    sed -i 's/\bdos2unix\b/true/g' "${cache_dir}/util_functions.sh"
    magisk_hostify_util_functions "${cache_dir}/util_functions.sh"
  fi
  if [[ -f "${extract_dir}/assets/stub.apk" ]]; then
    cp -f "${extract_dir}/assets/stub.apk" "${cache_dir}/stub.apk"
  fi

  host_dir="$(magisk_host_lib_dir "$extract_dir")"
  if [[ -z "$host_dir" || ! -f "${host_dir}/libmagiskboot.so" ]]; then
    rm -rf "$extract_dir"
    die "Magisk APK missing host libmagiskboot.so for $(uname -m)"
  fi
  # Host-arch magiskboot unpacks/repacks on the build machine.
  cp -f "${host_dir}/libmagiskboot.so" "${cache_dir}/magiskboot"
  chmod +x "${cache_dir}/magiskboot"

  arm_dir="${extract_dir}/lib/armeabi-v7a"
  if [[ ! -d "$arm_dir" ]]; then
    rm -rf "$extract_dir"
    die "Magisk APK has no armeabi-v7a libs; v4xx (msm8226) requires a Magisk build with 32-bit ARM support"
  fi

  if [[ -f "${arm_dir}/libmagiskinit.so" ]]; then
    cp -f "${arm_dir}/libmagiskinit.so" "${cache_dir}/magiskinit"
  else
    rm -rf "$extract_dir"
    die "Magisk APK missing lib/armeabi-v7a/libmagiskinit.so"
  fi
  chmod +x "${cache_dir}/magiskinit"

  if [[ -f "${arm_dir}/libmagisk.so" ]]; then
    cp -f "${arm_dir}/libmagisk.so" "${cache_dir}/magisk"
    cp -f "${arm_dir}/libmagisk.so" "${cache_dir}/magisk32"
  elif [[ -f "${arm_dir}/libmagisk32.so" ]]; then
    cp -f "${arm_dir}/libmagisk32.so" "${cache_dir}/magisk32"
    cp -f "${arm_dir}/libmagisk32.so" "${cache_dir}/magisk"
  else
    rm -rf "$extract_dir"
    die "Magisk APK missing lib/armeabi-v7a/libmagisk.so or libmagisk32.so"
  fi
  chmod +x "${cache_dir}/magisk" "${cache_dir}/magisk32"

  if [[ -f "${arm_dir}/libinit-ld.so" ]]; then
    cp -f "${arm_dir}/libinit-ld.so" "${cache_dir}/init-ld"
    chmod +x "${cache_dir}/init-ld"
  fi

  # Device-arch helpers only — never overwrite host magiskboot with ARM.
  if [[ -f "${arm_dir}/libmagiskpolicy.so" ]]; then
    cp -f "${arm_dir}/libmagiskpolicy.so" "${cache_dir}/magiskpolicy"
    chmod +x "${cache_dir}/magiskpolicy"
  fi

  cp -f "$apk" "${cache_dir}/source.apk" 2>/dev/null || true
  touch "$stamp"
  rm -rf "$extract_dir"
  info "Magisk tools prepared in ${cache_dir}"
  printf '%s' "$cache_dir"
}

patch_bootimage_with_magisk() {
  local product="$1"
  local src dest tools_dir workdir
  src="${RELEASE_DIR}/lineage-14.1-boot-${product}.img"
  [[ -f "$src" ]] || die "Unpatched boot image missing: ${src}"

  tools_dir="$(ensure_magisk_tools "$MAGISK_APK")"
  workdir="$(mktemp -d /tmp/v4xx-magisk-XXXX)"
  cp -a "${tools_dir}/." "$workdir/"
  cp -f "$src" "${workdir}/boot.img"
  # Prefer workdir binaries; provide a dos2unix stub if the host lacks it.
  if ! command -v dos2unix >/dev/null 2>&1; then
    cat >"${workdir}/dos2unix" <<'EOF'
#!/bin/sh
# Minimal dos2unix stand-in for Magisk scripts on bare build hosts.
for f in "$@"; do
  [ -f "$f" ] || continue
  sed -i 's/\r$//' "$f"
done
EOF
    chmod +x "${workdir}/dos2unix"
  fi

  info "Patching boot.img with Magisk for ${product}..."
  (
    cd "$workdir"
    export PATH="${workdir}:${PATH}"
    export KEEPVERITY=true
    export KEEPFORCEENCRYPT=true
    sh ./boot_patch.sh ./boot.img
  )

  [[ -f "${workdir}/new-boot.img" ]] ||
    die "Magisk boot_patch.sh did not produce new-boot.img"

  dest="${RELEASE_DIR}/lineage-14.1-boot-${product}-magisk.img"
  cp -f "${workdir}/new-boot.img" "$dest"
  rm -rf "$workdir"
  info "Copied Magisk-patched boot -> ${dest}"
  ls -lh "$dest"
}

validate_magisk_opts() {
  [[ "$PATCH_MAGISK" -eq 1 ]] || return 0
  [[ "$BUILD_TYPE" == "lineage" ]] || die "--magisk requires --type lineage"
  command -v unzip >/dev/null 2>&1 ||
    die "unzip is required for Magisk patching (apt install unzip)"
  [[ -n "$MAGISK_APK" ]] ||
    die "--magisk requires --magisk-apk PATH (or set MAGISK_APK in ${CONF_FILE})"
  [[ -f "$MAGISK_APK" ]] || die "Magisk APK not found: ${MAGISK_APK}"
  MAGISK_APK="$(cd "$(dirname "$MAGISK_APK")" && pwd)/$(basename "$MAGISK_APK")"
}

patch_selected_devices_magisk() {
  if [[ "$DEVICE" == "all" ]]; then
    local d
    for d in "${DEVICES[@]}"; do
      patch_bootimage_with_magisk "$d"
    done
    return
  fi

  local d valid=0
  for d in "${DEVICES[@]}"; do
    if [[ "$DEVICE" == "$d" ]]; then
      valid=1
      break
    fi
  done
  [[ "$valid" -eq 1 ]] ||
    die "Unknown device '${DEVICE}' (expected: ${DEVICES[*]}|all)"
  patch_bootimage_with_magisk "$DEVICE"
}

build_device() {
  local product="$1"
  local target="lineage_${product}-${LUNCH_VARIANT}"

  if [[ "$BUILD_BOOTIMAGE" -eq 1 && "$BUILD_TYPE" != "lineage" ]]; then
    die "--bootimage is only supported for --type lineage"
  fi
  if [[ "$BUILD_BOOTIMAGE" -eq 1 && "$NO_CLOBBER" -eq 0 ]]; then
    warn "--bootimage implies --no-clobber (skipping make clobber)"
    NO_CLOBBER=1
  fi

  ensure_source_dir
  ensure_vendorsetup
  set_build_env
  if [[ "$BUILD_BOOTIMAGE" -eq 1 ]]; then
    info "Building bootimage for ${product} (${target}, jobs=${JOBS})"
  else
    info "Building ${BUILD_TYPE} for ${product} (${target}, jobs=${JOBS})"
  fi

  # envsetup / lunch / mka freely reference unset vars (TOP, etc.).
  # Keep nounset off for the entire Android build phase.
  set +u
  if [[ "$NO_CLOBBER" -eq 0 ]]; then
    info "make clobber (clean, reproducible output)..."
    # Clean the disk-backed out/ before hiding it with an optional tmpfs.
    # shellcheck disable=SC1091
    source build/envsetup.sh
    lunch "$target"
    make -j"$JOBS" clobber
  else
    warn "Skipping make clobber (--no-clobber)"
  fi

  if [[ "$BUILD_BOOTIMAGE" -eq 0 ]]; then
    prepare_out_tmpfs
    configure_jack_server
  fi

  # Re-source after clobber/tmpfs so all generated files go to the active out/.
  # shellcheck disable=SC1091
  source build/envsetup.sh
  lunch "$target"

  if [[ "$BUILD_TYPE" == "twrp" ]]; then
    make -j"$JOBS" recoveryimage
    set -u
    copy_twrp_artifact "$product"
  elif [[ "$BUILD_BOOTIMAGE" -eq 1 ]]; then
    mka bootimage
    set -u
    copy_lineage_bootimage "$product"
    if [[ "$PATCH_MAGISK" -eq 1 ]]; then
      patch_bootimage_with_magisk "$product"
    fi
  else
    # mka already picks a job count; pass bacon only
    mka bacon
    set -u
    copy_lineage_artifacts "$product"
  fi
}

build_selected_devices() {
  if [[ "$DEVICE" == "all" ]]; then
    local d
    for d in "${DEVICES[@]}"; do
      build_device "$d"
    done
    return
  fi

  local d valid=0
  for d in "${DEVICES[@]}"; do
    [[ "$DEVICE" == "$d" ]] && valid=1
  done
  [[ "$valid" -eq 1 ]] ||
    die "Unknown device '${DEVICE}' (expected: ${DEVICES[*]}|all)"
  build_device "$DEVICE"
}

type_menu() {
  local type="$1"
  select_type "$type"
  while true; do
    echo
    echo "${BUILD_TYPE} - LG G Pad 7 (v4xx)"
    echo "  Source:  ${SOURCE_DIR:-<not configured>}"
    echo "  Release: ${RELEASE_DIR}"
    echo
    echo "  1) Build v400"
    echo "  2) Build v410"
    echo "  3) Build v480"
    echo "  4) Build v490"
    echo "  5) Build ALL devices"
    echo "  6) Sync sources (full tree)"
    echo "  7) Sync specific project(s)"
    echo "  8) Configure source tree"
    if [[ "$BUILD_TYPE" == "lineage" ]]; then
      echo "  9) Build bootimage only"
      echo " 10) Patch existing boot.img with Magisk"
    fi
    echo "  b) Back"
    read -r -p "Select: " choice
    case "$choice" in
      1|2|3|4)
        DEVICE="${DEVICES[$((choice - 1))]}"
        build_selected_devices
        DEVICE=""
        ;;
      5) DEVICE=all; build_selected_devices; DEVICE="" ;;
      6)
        SYNC_PROJECTS=()
        sync_sources
        ;;
      7)
        SYNC_PROJECTS=()
        echo "Enter repo path(s) relative to source root (space-separated)."
        echo "Examples: kernel/lge/v4xx  device/lge/v4xx-common"
        read -r -p "Project(s): " project_line
        # shellcheck disable=SC2206
        SYNC_PROJECTS=(${project_line})
        [[ ${#SYNC_PROJECTS[@]} -gt 0 ]] || {
          warn "No projects given"
          continue
        }
        sync_sources
        SYNC_PROJECTS=()
        ;;
      8)
        read -r -p "${BUILD_TYPE} source directory: " REQUESTED_SOURCE_DIR
        select_type "$BUILD_TYPE"
        install_repo_tool
        setup_source_tree
        REQUESTED_SOURCE_DIR=""
        ;;
      9)
        if [[ "$BUILD_TYPE" != "lineage" ]]; then
          warn "Bootimage builds are lineage-only"
          continue
        fi
        echo "  1) v400  2) v410  3) v480  4) v490"
        read -r -p "Select device: " dev_choice
        case "$dev_choice" in
          1|2|3|4)
            DEVICE="${DEVICES[$((dev_choice - 1))]}"
            BUILD_BOOTIMAGE=1
            PATCH_MAGISK=0
            read -r -p "Patch boot.img with Magisk? [y/N]: " magisk_choice
            case "$magisk_choice" in
              y|Y|yes|Yes|YES)
                PATCH_MAGISK=1
                if [[ -z "$MAGISK_APK" ]]; then
                  read -r -p "Path to Magisk.apk: " MAGISK_APK
                fi
                validate_magisk_opts
                ;;
            esac
            build_selected_devices
            BUILD_BOOTIMAGE=0
            PATCH_MAGISK=0
            DEVICE=""
            ;;
          *) warn "Invalid selection" ;;
        esac
        ;;
      10)
        if [[ "$BUILD_TYPE" != "lineage" ]]; then
          warn "Magisk patching is lineage-only"
          continue
        fi
        echo "  1) v400  2) v410  3) v480  4) v490"
        read -r -p "Select device: " dev_choice
        case "$dev_choice" in
          1|2|3|4)
            DEVICE="${DEVICES[$((dev_choice - 1))]}"
            PATCH_MAGISK=1
            BUILD_BOOTIMAGE=0
            if [[ -z "$MAGISK_APK" ]]; then
              read -r -p "Path to Magisk.apk: " MAGISK_APK
            fi
            validate_magisk_opts
            patch_selected_devices_magisk
            PATCH_MAGISK=0
            DEVICE=""
            ;;
          *) warn "Invalid selection" ;;
        esac
        ;;
      b|B) return ;;
      *) warn "Invalid selection" ;;
    esac
  done
}

interactive_menu() {
  while true; do
    echo
    echo "LG G Pad 7 v4xx build menu"
    echo "  TWRP source:    ${TWRP_SOURCE_DIR:-<not configured>}"
    echo "  Lineage source: ${LINEAGE_SOURCE_DIR:-<not configured>}"
    echo "  Release:        ${RELEASE_DIR}"
    echo
    echo "  1) TWRP"
    echo "  2) LineageOS 14.1"
    echo "  3) Install shared host dependencies"
    echo "  q) Quit"
    read -r -p "Select: " choice
    case "$choice" in
      1) type_menu twrp ;;
      2) type_menu lineage ;;
      3) setup_host ;;
      q|Q) exit 0 ;;
      *) warn "Invalid selection" ;;
    esac
  done
}

main() {
  load_conf
  parse_args "$@"

  if [[ -n "$BUILD_TYPE" ]]; then
    select_type "$BUILD_TYPE"
  elif [[ -n "$REQUESTED_SOURCE_DIR" || "$DO_SYNC" -eq 1 ||
          ${#SYNC_PROJECTS[@]} -gt 0 || -n "$DEVICE" ]]; then
    die "--type twrp|lineage is required for source, sync, and build operations"
  fi

  if [[ "$DO_SETUP" -eq 1 ]]; then
    setup_host
    if [[ -n "$REQUESTED_SOURCE_DIR" ]]; then
      setup_source_tree
    fi
  elif [[ -n "$REQUESTED_SOURCE_DIR" ]]; then
    install_repo_tool
    setup_source_tree
  fi

  if [[ "$DO_SYNC" -eq 1 ]]; then
    sync_sources
  fi
  if [[ -n "$DEVICE" ]]; then
    validate_magisk_opts
    save_conf
    # --magisk without --bootimage patches an existing release boot.img only.
    if [[ "$PATCH_MAGISK" -eq 1 && "$BUILD_BOOTIMAGE" -eq 0 ]]; then
      patch_selected_devices_magisk
    else
      build_selected_devices
    fi
  fi

  if [[ "$DO_SETUP" -eq 0 && "$DO_SYNC" -eq 0 && -z "$DEVICE" &&
        -z "$REQUESTED_SOURCE_DIR" ]]; then
    interactive_menu
  fi
}

main "$@"
